name: CI

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - main

env:
  DEVELOPER_DIR: /Applications/Xcode_14.3.app/Contents/Developer

jobs:
  test:
    name: Test
    runs-on: macOS-13
    strategy:
      matrix:
        destination:
          - "platform=macOS"
          - "platform=iOS Simulator,name=iPhone 11"

    steps:
      - uses: actions/checkout@v3
      - name: Test platform ${{ matrix.destination }}
        run: set -o pipefail && xcodebuild -scheme LanguageClient -destination "${{ matrix.destination }}" test | xcpretty
